spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/banca
springdoc:
  api-docs:
    enabled: true
    path: /swagger-doc/swagger-ui.html
logging:
  level:
    com:
      nttdata:
        bancamicroservices: debug
eureka:
  cliente:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
