spring:
  data:
    mongodb:
      database: banca
      port: 27017
      host: localhost
springdoc:
  api-docs:
    enabled: true
    path: /swagger-doc/swagger-ui.html
logging:
  level:
    com:
      nttdata:
        bancamicroservices: debug
eureka:
  cliente:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
springdoc:
  swagger-ui:
    enabled: true
